### ISSUE TITLE
Kodi 18 / dependency on xbmc.python version 3.0.0 could not be satisfied

### ISSUE THREAD

**Issue by wail-fajr-rd** [BreizhReloaded/plugin.video.orange.fr#13]
Hello,
I read that your addon is only for Kodi 19 but I use a Raspberry 3 and could only install Libreelec 9.2.8 with Kodi 18.9.
I tried to install your addon (which is very promising to me) from a zip file and got an error "dependency on xbmc.python version 3.0.0 could not be satisfied". I understand that it is related to the fact that Kodi 19 requires Python 3 while Libreelec 9/Kodi 18 are Python 2 only.
I can try to port your addon to Kodi 18 although I am entirely new to Kodi addon programming and almost new to Python. Is it just about porting the code to Python 2 or is it more complex?

**Comment by BreizhReloaded** [comment]
Hello @wail-fajr-rd,

As said on #12, I don't have time to fully handle this topic for the moment. Porting the addon to Python 2 may be easy (and it is), it's only one part of the problem : I don't want to loose compatibility with Kodi 19 and Python 3. In order to publish both versions at the same time, I need to set up some pipelines when releasing a new version. I got some templates from the Kodi community, but I'm not very familiar with that part of GitHub, so it requires some time to learn how it works. Time I don't unfortunately have for the moment.

**Comment by wail-fajr-rd** [comment]
Oh I missed this discussion... I understand that you don't have time, everybody is busy these times but I can try to make some time for porting your addon. I will look myself into how to develop Kodi addons but any tips you may have on how to that port will be very appreciated (including things as how to build/test the code). As I said, I am almost new to Python and entirely new to IPTV/Kodi programming.

**Comment by BreizhReloaded** [comment]
No problem. Main things to update are:
- system import for libraries like urllib (syntax changes a lot between 2 and 3)
- new language feature like f-strings

I would recommand to install Python 2 on your machine, so you can run pylint and easily detect what's not supported. Then run the addon within Kodi and use the logs.

**Comment by BreizhReloaded** [comment]
Discussion continues on #12
